// Room data structure based on the booking lists

export type RoomStatus = "Vacant" | "Confirmed" | "Rented";

export type RoomType = "Shop Room" | "Business Centre" | "Food Court" | "Gym" | "Super Market";

export interface ShopRoom {
  id: string;
  number: number | string;
  name: string;
  regNo: string;
  shopDetails: string;
  rentPerSqFt: number;
  status: RoomStatus;
  location: string;
  remarks?: string;
  block: "A Block" | "B Block";
  floor?: string;
  imageUrl?: string;
  floorImageUrl?: string;
}

export interface BusinessCentreRoom {
  id: string;
  number: number | string;
  name: string;
  rate: number;
  type: "MINI ROOMS" | "LARGE ROOMS" | "DAILY WORK SPACE" | "WEEKLY WORK SPACE" | "WORK SPACE MONTHLY" | "S.P WORK SPACE";
  quantity: number;
  totalAmount: number;
  location: string;
  remarks?: string;
  block: "A Block" | "B Block";
  status: RoomStatus;
  imageUrl?: string;
  floorImageUrl?: string;
}

export type Room = ShopRoom | BusinessCentreRoom;

// Sample data based on the booking sheets
export const shopRooms: ShopRoom[] = [
  {
    id: "a-1",
    number: 1,
    name: "EXECUTIVE DIRECTORS",
    regNo: "-",
    shopDetails: "ROOF GARDEN RESTAURENT",
    rentPerSqFt: 20,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block / Roof Garden",
    block: "A Block",
    floor: "Roof",
  },
  {
    id: "a-2",
    number: 2,
    name: "VACANT",
    regNo: "-",
    shopDetails: "NEED A FRIED CHICKEN SHOP",
    rentPerSqFt: 80,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-3",
    number: 3,
    name: "YOUSUF",
    regNo: "350",
    shopDetails: "JUICE CENTRE & SHAVARMA",
    rentPerSqFt: 60,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-4",
    number: 4,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED BURGER SHOP",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-5",
    number: 5,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A VARITY OF SNACKS WITH TEA",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-6",
    number: 6,
    name: "FOR ROOF",
    regNo: "-",
    shopDetails: "SEMI KITCHEN FOR ROOF RESTAURENT",
    rentPerSqFt: 20,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
    floor: "Roof",
  },
  {
    id: "a-7",
    number: 7,
    name: "VACANT",
    regNo: "NEED A",
    shopDetails: "COMPUTER GAME CENTRE",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "LEFT SIDE",
    remarks: "LEFT SIDE",
    block: "A Block",
  },
  {
    id: "a-8",
    number: 8,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "GENTS FATION (Road View)",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "(Road View)",
    remarks: "(Road View)",
    block: "A Block",
  },
  {
    id: "a-9",
    number: 9,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED AN OPTICAL SHOP",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-10",
    number: 10,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A GENTS SALON",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-11",
    number: 11,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A STUDIO",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-12",
    number: 12,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A LAUNDERY SHOP",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "RIGHT SIDE LAST",
    remarks: "RIGHT SIDE LAST",
    block: "A Block",
  },
  {
    id: "a-13",
    number: 13,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A MOBILE SHOP",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-14",
    number: 14,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A COMPUTER SHOP",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-15",
    number: 15,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A TAILORING",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-16",
    number: 16,
    name: "ABDUL RASHEED",
    regNo: "D1",
    shopDetails: "TRAVEL AGENCY (Road View)",
    rentPerSqFt: 70,
    status: "Confirmed",
    location: "(Road View)",
    remarks: "(Road View)",
    block: "A Block",
  },
  {
    id: "a-17",
    number: 17,
    name: "ALIKKUTTY",
    regNo: "D6",
    shopDetails: "OUD SHOP",
    rentPerSqFt: 60,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-18",
    number: 18,
    name: "SAKEER",
    regNo: "D 12",
    shopDetails: "GENTS WEAR",
    rentPerSqFt: 60,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-19",
    number: 19,
    name: "ABDUL RAZACK",
    regNo: "D19,38 AND 251",
    shopDetails: "JEWELLERAY",
    rentPerSqFt: 60,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  {
    id: "a-20",
    number: 20,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A ROSTERY SHOP",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "RIGHT SIDE LAST",
    remarks: "RIGHT SIDE LAST",
    block: "A Block",
  },
  {
    id: "a-21",
    number: 21,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A FOOT WEAR",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "LEFT SIDE",
    remarks: "LEFT SIDE",
    block: "A Block",
  },
  {
    id: "a-22",
    number: 22,
    name: "VACANT",
    regNo: "VACANT",
    shopDetails: "NEED A CROCKERY SHOP",
    rentPerSqFt: 70,
    status: "Vacant",
    location: "LEFT SIDE",
    remarks: "LEFT SIDE",
    block: "A Block",
  },
  {
    id: "a-23",
    number: 23,
    name: "SHAFEEQ C.",
    regNo: "57",
    shopDetails: "GULF BAZAR SHOP",
    rentPerSqFt: 60,
    status: "Confirmed",
    location: "A & Block",
    remarks: "A & Block",
    block: "A Block",
  },
  // B Block shops
  {
    id: "b-24",
    number: 24,
    name: "MALE GYM",
    regNo: "-",
    shopDetails: "GYM",
    rentPerSqFt: 0,
    status: "Confirmed",
    location: "B BLOCK / 2nd FLOOR",
    remarks: "B BLOCK / 2nd FLOOR",
    block: "B Block",
    floor: "2nd Floor",
  },
  {
    id: "b-32",
    number: 32,
    name: "VACANT",
    regNo: "-",
    shopDetails: "NEED LADIES FOOT WEAR",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER / Area 350",
    block: "B Block",
    floor: "Ladies Corner",
  },
  {
    id: "b-33",
    number: 33,
    name: "RAMSI",
    regNo: "D 16",
    shopDetails: "GIFT AND CHILD WEARS",
    rentPerSqFt: 50,
    status: "Confirmed",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER",
    block: "B Block",
    floor: "Ladies Corner",
  },
  {
    id: "b-34",
    number: 34,
    name: "VACANT",
    regNo: "-",
    shopDetails: "NEED A FANCY CENTRE",
    rentPerSqFt: 60,
    status: "Vacant",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER / Area 250",
    block: "B Block",
    floor: "Ladies Corner",
  },
  {
    id: "b-35",
    number: 35,
    name: "NASAR MULLAMPARA",
    regNo: "D20",
    shopDetails: "LADIES INNER WARES",
    rentPerSqFt: 50,
    status: "Confirmed",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER",
    block: "B Block",
    floor: "Ladies Corner",
  },
  {
    id: "b-36",
    number: 36,
    name: "RASHEED A.P",
    regNo: "D1",
    shopDetails: "LADIES DRESS WEARS",
    rentPerSqFt: 50,
    status: "Confirmed",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER",
    block: "B Block",
    floor: "Ladies Corner",
  },
  {
    id: "b-37",
    number: 37,
    name: "NAIZAM EDAVANNA",
    regNo: "-",
    shopDetails: "NARDAS BRIDAL, SALON AND GYM",
    rentPerSqFt: 50,
    status: "Confirmed",
    location: "LADIES CORNER",
    remarks: "LADIES CORNER",
    block: "B Block",
    floor: "Ladies Corner",
  },
];

export const businessCentreRooms: BusinessCentreRoom[] = [
  {
    id: "bc-25",
    number: 25,
    name: "VACANT",
    rate: 10000,
    type: "MINI ROOMS",
    quantity: 13,
    totalAmount: 130000,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
  {
    id: "bc-27",
    number: 27,
    name: "VACANT",
    rate: 13000,
    type: "LARGE ROOMS",
    quantity: 3,
    totalAmount: 39000,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
  {
    id: "bc-28",
    number: 28,
    name: "VACANT",
    rate: 300,
    type: "DAILY WORK SPACE",
    quantity: 2,
    totalAmount: 600,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
  {
    id: "bc-29",
    number: 29,
    name: "VACANT",
    rate: 3000,
    type: "WEEKLY WORK SPACE",
    quantity: 2,
    totalAmount: 6000,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
  {
    id: "bc-30",
    number: 30,
    name: "VACANT",
    rate: 6000,
    type: "WORK SPACE MONTHLY",
    quantity: 12,
    totalAmount: 72000,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
  {
    id: "bc-31",
    number: 31,
    name: "VACANT",
    rate: 8000,
    type: "S.P WORK SPACE",
    quantity: 8,
    totalAmount: 64000,
    location: "B BLOCK",
    remarks: "B BLOCK",
    block: "B Block",
    status: "Vacant",
  },
];

export const allRooms: Room[] = [...shopRooms, ...businessCentreRooms];

// Helper functions
export function isShopRoom(room: Room): room is ShopRoom {
  return "rentPerSqFt" in room && "shopDetails" in room;
}

export function isBusinessCentreRoom(room: Room): room is BusinessCentreRoom {
  return "type" in room && "rate" in room && "quantity" in room;
}

